project_id = "icvncmawahwbpiohrcxv"

[api]
enabled = true
# Port for the REST API
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of the API
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from the API
max_rows = 1000

[db]
# Port for the Postgres database
port = 54322
# The shadow port is used for Supabase Branching and is required for diffing
shadow_port = 54320
# Major version of the database
major_version = 17

[studio]
enabled = true
port = 54323
# API URL of the Studio
api_url = "http://localhost:54323/api"

# Email testing server
[inbucket]
enabled = true
port = 54324
# SMTP credentials for local development
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = 52428800 # 50MB

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[auth.external.github]
enabled = true
client_id = "env(SUPABASE_AUTH_GITHUB_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GITHUB_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"

# Enable experimental features
[experimental]

