name: blindly_dating_app
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^17.0.1

  # Backend & Auth
  supabase_flutter: ^2.12.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.0.0
  firebase_app_check: ^0.3.1
  http: ^1.1.0

  # Utils
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  uuid: ^4.3.3
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.3.2
  
  # Security (Added for your Task 5)
  safe_device: ^1.1.4 
  flutter_secure_storage: ^10.0.0

  # UI/Icons
  cupertino_icons: ^1.0.8
  sentry_flutter: ^8.14.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

dependency_overrides:
  fluttertoast: ^8.2.9

flutter:
  uses-material-design: true

  # Assets
  assets:
    - .env